<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN436923" failures="2" tests="16" name="com.selenium.test.testCases.TestMain" time="10.967" errors="0" timestamp="2025-06-21T21:52:56 IST" skipped="0">
  <testcase classname="com.selenium.test.testCases.TestMain" name="testURL" time="0.150"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testTitle" time="0.399"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="alertHandle" time="0.012"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testURL" time="0.353"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="alertHandle" time="0.021"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testTitle" time="0.113"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testSrcStation" time="0.720"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testSrcStation" time="0.599"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDestStation" time="1.033"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDestStation" time="0.804"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDateSelection" time="1.509">
    <failure message="expected [25-Jun-25 Wed] but found [TEXT(TODAY()+4, &quot;dd-mmm-yy ddd&quot;)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [25-Jun-25 Wed] but found [TEXT(TODAY()+4, "dd-mmm-yy ddd")]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.selenium.test.testCases.TestMain.testDateSelection(TestMain.java:187)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testDateSelection -->
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDateSelection" time="1.435">
    <failure message="expected [25-Jun-25 Wed] but found [TEXT(TODAY()+4, &quot;dd-mmm-yy ddd&quot;)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [25-Jun-25 Wed] but found [TEXT(TODAY()+4, "dd-mmm-yy ddd")]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.selenium.test.testCases.TestMain.testDateSelection(TestMain.java:187)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testDateSelection -->
  <testcase classname="com.selenium.test.testCases.TestMain" name="selectChoices" time="1.133"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="selectChoices" time="1.472"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="availableTrain" time="0.583"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="availableTrain" time="0.631"/>
</testsuite> <!-- com.selenium.test.testCases.TestMain -->
